print("Network adress \t\t" + binary_to_decimal(net_addr) + "\t\t" + binary_to_string(net_addr))
print("Network class: \t\t" + get_network_class(ip_to_binary(adress)))
print("Network type: \t\t" + pool_determination(adress[0:4]))
print("Network mask: \t\t" + binary_to_decimal(mask_to_binary(int(mask))) + "\t\t" + binary_to_string(mask_to_binary(int(mask))))
print("Broadcast address: \t" + binary_to_decimal(broad_addr) + "\t\t" + binary_to_string(broad_addr))
print("First host address: \t" + binary_to_decimal(get_first_host(net_addr)) + "\t\t" + binary_to_string(get_first_host(net_addr)))
print("Last host address: \t" + binary_to_decimal(get_last_host(broad_addr)) + "\t\t" + binary_to_string(get_last_host(broad_addr)))
print("Max number of hosts: \t" + get_max_hosts(mask_to_binary(int(mask))))


array_output.append("IP Address: \t\t" + ip + "\t\t" + binary_to_string(ip_to_binary(adress)) +"\n")
array_output.append("CIDR: \t\t\t" + mask + "\t\t\t" + binary_to_string(mask_to_binary(int(mask)))+"\n")
array_output.append("Network adress \t\t" + binary_to_decimal(net_addr) + "\t\t" + binary_to_string(net_addr)+"\n")
array_output.append("Network class: \t\t" + get_network_class(ip_to_binary(adress))+"\n")
array_output.append("Network type: \t\t" + pool_determination(adress[0:4])+"\n")
array_output.append("Network mask: \t\t" + binary_to_decimal(mask_to_binary(int(mask))) + "\t\t" + binary_to_string(mask_to_binary(int(mask)))+"\n")
array_output.append("Broadcast address: \t" + binary_to_decimal(broad_addr) + "\t\t" + binary_to_string(broad_addr)+"\n")
array_output.append("First host address: \t" + binary_to_decimal(get_first_host(net_addr)) + "\t\t" + binary_to_string(get_first_host(net_addr))+"\n")
array_output.append("Last host address: \t" + binary_to_decimal(get_last_host(broad_addr)) + "\t\t" + binary_to_string(get_last_host(broad_addr))+"\n")
array_output.append("Max number of hosts: \t" + get_max_hosts(mask_to_binary(int(mask))))